//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanovKursovaya.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Id_Training { get; set; }
        public int Id_Client { get; set; }
        public Nullable<int> Id_DogHandler { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual DogHandler DogHandler { get; set; }
        public virtual Training Training { get; set; }
    }
}
